### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by deepakrokz** [imshyam/mintube#38]
Hi @imshyam ,
I am getting this type of error while playing anything within the app 

> An error occurred. Please try again later.
(Playback ID: nhewjhrDherw283) LearnMore

from 2 weeks. I checked on several devices, can you please check and fix it. I will be very thankful to you.

**Comment by BonnieSawe** [comment]
You got a solution?

**Comment by deepakrokz** [comment]
No, I haven't. Still looking for a solution.

**Comment by imshyam** [comment]
@deepakrokz @BonnieSawe I'll look into it, and will update.

**Comment by BonnieSawe** [comment]
thanks @imshyam

**Comment by deepakrokz** [comment]
Hi @imshyam , 

any update on this?

**Comment by imshyam** [comment]
@deepakrokz it works when you share a video to mintube, like share from YouTube to mintube. Can you confirm this?

I'll figure out why it works for that only. And will update as I get a solution. 

Thank you.

**Comment by BonnieSawe** [comment]
It does that in all videos @imshyam

**Comment by deepakrokz** [comment]
Yes, shared videos are working but for each video quality is being changed to default all the time, while it should be at specified for each video.
Thanks for your reply, looking forward for the fixes.

**Comment by andi4work** [comment]
*WHEN I CLICK ON VIDEO TO PLAY APP CRASHING...*`10-19** 10:13:34.092 11297-11297/com.shapps.mintubeapp D/Main Page Finished: https://m.youtube.com/results?q=food
10-19 10:13:35.282 11297-11561/com.shapps.mintubeapp D/Yay Catches!!!!: https://m.youtube.com/watch?v=7UU36KzhYTc&pbj=1&lact=1&itct=CCMQpDAYACITCLjyn97Ykd4CFQRNfAodAOQN7DIGc2VhcmNoUgRmb29k&csn=9mDJW5D2Fpe01AbYkwU
10-19 10:13:35.282 11297-11561/com.shapps.mintubeapp D/VID: tps://m.youtube.com/watch?v=7UU36KzhYTc&pbj=1&lact=1&itct=CCMQpDAYACITCLjyn97Ykd4CFQRNfAodAOQN7DIGc2VhcmNoUgRmb29k&csn=9mDJW5D2Fpe01AbYkwU
10-19 10:13:35.284 11297-11561/com.shapps.mintubeapp D/ListID: ://m.youtube.com/watch?v=7UU36KzhYTc&pbj=1&lact=1&itct=CCMQpDAYACITCLjyn97Ykd4CFQRNfAodAOQN7DIGc2VhcmNoUgRmb29k&csn=9mDJW5D2Fpe01AbYkwU
10-19 10:13:35.284 11297-11561/com.shapps.mintubeapp D/Not a: Playlist.
10-19 10:13:35.294 11297-11297/com.shapps.mintubeapp D/Service: Started!
10-19 10:13:35.300 11297-11297/com.shapps.mintubeapp W/Notification: Use of stream types is deprecated for operations other than volume control
    See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
10-19 10:13:35.300 11297-11297/com.shapps.mintubeapp D/Setting: Image, Title, Author
10-19 10:13:35.459 11297-11492/com.shapps.mintubeapp W/System.err: java.io.FileNotFoundException: https://i.ytimg.com/vi/tps://m.youtube.com/watch?v=7UU36KzhYTc&pbj=1&lact=1&itct=CCMQpDAYACITCLjyn97Ykd4CFQRNfAodAOQN7DIGc2VhcmNoUgRmb29k&csn=9mDJW5D2Fpe01AbYkwU/mqdefault.jpg
10-19 10:13:35.460 11297-11492/com.shapps.mintubeapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.shapps.mintubeapp.AsyncTask.ImageLoadTask.doInBackground(ImageLoadTask.java:31)
        at com.shapps.mintubeapp.AsyncTask.ImageLoadTask.doInBackground(ImageLoadTask.java:15)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
10-19 10:13:36.203 11297-11517/com.shapps.mintubeapp W/System.err: java.io.FileNotFoundException: https://www.youtube.com/oembed?url=http://www.youtu.be/watch?v=tps://m.youtube.com/watch?v=7UU36KzhYTc&pbj=1&lact=1&itct=CCMQpDAYACITCLjyn97Ykd4CFQRNfAodAOQN7DIGc2VhcmNoUgRmb29k&csn=9mDJW5D2Fpe01AbYkwU&format=json
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.shapps.mintubeapp.AsyncTask.LoadDetailsTask.doInBackground(LoadDetailsTask.java:32)
        at com.shapps.mintubeapp.AsyncTask.LoadDetailsTask.doInBackground(LoadDetailsTask.java:16)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
10-19 10:13:36.204 11297-11297/com.shapps.mintubeapp W/System.err: org.json.JSONException: End of input at character 0 of 
        at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
        at org.json.JSONTokener.nextValue(JSONTokener.java:97)
10-19 10:13:36.205 11297-11297/com.shapps.mintubeapp W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:159)
        at org.json.JSONObject.<init>(JSONObject.java:176)
        at com.shapps.mintubeapp.PlayerService.setImageTitleAuthor(PlayerService.java:712)
        at com.shapps.mintubeapp.PlayerService.doThis(PlayerService.java:371)
        at com.shapps.mintubeapp.PlayerService.onStartCommand(PlayerService.java:228)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-19 10:13:36.255 11297-11297/com.shapps.mintubeapp D/Starting: Single Video!!!
    
    --------- beginning of system
10-19 10:13:36.335 11297-11297/com.shapps.mintubeapp I/Choreographer: Skipped 62 frames!  The application may be doing too much work on its main thread.
10-19 10:13:36.383 11297-11297/com.shapps.mintubeapp D/ChatHead Size: 180
10-19 10:13:36.401 11297-11297/com.shapps.mintubeapp D/Player W and H: 720 627
10-19 10:13:36.413 11297-11297/com.shapps.mintubeapp D/Close Image Size: 300
10-19 10:13:36.461 11297-11356/com.shapps.mintubeapp I/OpenGLRenderer: Davey! duration=1167ms; Flags=1, IntendedVsync=25642649612908, Vsync=25643682946200, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=25643692075953, AnimationStart=25643692350953, PerformTraversalsStart=25643721025953, DrawStart=25643769727953, SyncQueued=25643769961953, SyncStart=25643770206953, IssueDrawCommandsStart=25643770269953, SwapBuffers=25643815510953, FrameCompleted=25643817352953, DequeueBufferDuration=383000, QueueBufferDuration=588000, 
10-19 10:13:36.463 11297-11297/com.shapps.mintubeapp D/Main Page Loading: https://m.youtube.com/
10-19 10:13:36.474 11297-11356/com.shapps.mintubeapp D/EGL_emulation: eglMakeCurrent: 0xdf9854e0: ver 3 0 (tinfo 0xdf983760)
10-19 10:13:36.667 11297-11356/com.shapps.mintubeapp I/chatty: uid=10085(com.shapps.mintubeapp) RenderThread identical 4 lines
10-19 10:13:36.735 11297-11356/com.shapps.mintubeapp D/EGL_emulation: eglMakeCurrent: 0xdf9854e0: ver 3 0 (tinfo 0xdf983760)
10-19 10:13:37.361 11297-11297/com.shapps.mintubeapp D/Main Page Finished: https://m.youtube.com/
10-19 10:13:37.938 11297-11356/com.shapps.mintubeapp D/EGL_emulation: eglMakeCurrent: 0xdf9854e0: ver 3 0 (tinfo 0xdf983760)
`

**Comment by imshyam** [comment]
Please try now. Fixed.

**Comment by deepakrokz** [comment]
Hi @imshyam,

Thanks for the update and sorry for the delay in reply.
Yes, it's working now but the thing is video quality control keeps changing on each song to higher.
Can you please look into the same as well.

Thank you.
